# Generated by Django 6.0.8 on 2026-08-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('clasificacion', models.CharField(choices=[('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('B15', 'B15'), ('C', 'C'), ('D', 'D')], max_length=5)),
                ('genero', models.CharField(choices=[('accion', 'Acción'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('ciencia_ficcion', 'Ciencia ficción'), ('animacion', 'Animación')], max_length=20)),
                ('fecha_estreno', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='peliculas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
