# Generated by Django 6.0.8 on 2026-08-16 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
                ('sinopsis', models.TextField(verbose_name='Sinópsis')),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos', verbose_name='Duración')),
                ('clasificacion', models.CharField(choices=[('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('B15', 'B15'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='Clasificación')),
                ('genero', models.CharField(choices=[('accion', 'Acción'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('ciencia_ficcion', 'Ciencia ficción'), ('animacion', 'Animación')], max_length=20, verbose_name='Género')),
                ('fecha_estreno', models.DateField(verbose_name='Fecha de estreno')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='peliculas/', verbose_name='Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
